// code/convert-code/login-form/Vue3/LoginForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <div>
      <label>Email:</label>
      <input type="email" v-model="email" />
      <div v-if="errors.email" style="color: red">{{ errors.email }}</div>
    </div>
    <div>
      <label>Password:</label>
      <input type="password" v-model="password" />
      <div v-if="errors.password" style="color: red">{{ errors.password }}</div>
    </div>
    <button type="submit">Login</button>
  </form>
</template>

<script>
import { ref } from 'vue';

export default {
  setup() {
    const email = ref('');
    const password = ref('');
    const errors = ref({});

    const validateForm = () => {
      let isValid = true;
      const currentErrors = {};

      if (!email.value) {
        isValid = false;
        currentErrors.email = "Email is required";
      } else if (!/\S+@\S+\.\S+/.test(email.value)) {
        isValid = false;
        currentErrors.email = "Email is invalid";
      }

      if (!password.value) {
        isValid = false;
        currentErrors.password = "Password is required";
      }

      errors.value = currentErrors;
      return isValid;
    };

    const handleSubmit = () => {
      if (validateForm()) {
        console.log('Submitting', { email: email.value, password: password.value });
        // Add here your submission logic, e.g., calling an API
      }
    };

    return { email, password, errors, handleSubmit };
  }
};
</script>

// code/convert-code/login-form/LoginFormComponent.jsx
import React from 'react';

class LoginForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
      errors: {}
    };
  }

  validateForm = () => {
    let isValid = true;
    const errors = {};

    if (!this.state.email) {
      isValid = false;
      errors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(this.state.email)) {
      isValid = false;
      errors.email = "Email is invalid";
    }

    if (!this.state.password) {
      isValid = false;
      errors.password = "Password is required";
    }

    this.setState({ errors });
    return isValid;
  };

  handleSubmit = (event) => {
    event.preventDefault();
    if (this.validateForm()) {
      console.log('Submitting', { email: this.state.email, password: this.state.password });
      // Add here your submission logic, e.g., calling an API
    }
  };

  handleEmailChange = (event) => {
    this.setState({ email: event.target.value });
  };

  handlePasswordChange = (event) => {
    this.setState({ password: event.target.value });
  };

  render() {
    const { email, password, errors } = this.state;
    return (
      <form onSubmit={this.handleSubmit}>
        <div>
          <label>Email:</label>
          <input
            type="email"
            value={email}
            onChange={this.handleEmailChange}
          />
          {errors.email && <div style={{ color: 'red' }}>{errors.email}</div>}
        </div>
        <div>
          <label>Password:</label>
          <input
            type="password"
            value={password}
            onChange={this.handlePasswordChange}
          />
          {errors.password && <div style={{ color: 'red' }}>{errors.password}</div>}
        </div>
        <button type="submit">Login</button>
      </form>
    );
  }
}

export default LoginForm;
